name: Build Tweak Rootless

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid

      - name: Clone Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Download iOS 16.5 SDK
        run: |
          mkdir -p $HOME/theos/sdks
          curl -L "https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz" -o sdk.tar.xz
          tar -xf sdk.tar.xz -C $HOME/theos/sdks
          rm sdk.tar.xz

      - name: Build Rootless DEB
        run: |
          export THEOS=$HOME/theos
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VietMapDuoDash-DEB
          path: packages/*.deb
          if-no-files-found: error
